//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\medir_y_enviar.py
///  Source class: Aparato
///  Generation timestamp: 2019-06-05T07:47:06.526517
///  Class code hash: b21abe376dc9b9ca0e8bcf26c5aec27723597706
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_bridge_h
#define inodriver_bridge_h

#include <Arduino.h>

#include "SerialCommand.h"

#include "inodriver_user.h"

const char COMPILE_DATE_TIME[] = __DATE__ " " __TIME__;

void ok();
void error(const char*);
void error_i(int);
void bridge_loop();
void bridge_setup();

void getInfo();
void unrecognized(const char *);
void wrapperGet_ENABLE(); 
void wrapperSet_ENABLE(); 
void wrapperGet_Tension(); 


#endif // inodriver_bridge_h