//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\medir_y_enviar.py
///  Source class: Aparato
///  Generation timestamp: 2019-06-05T07:47:06.526517
///  Class code hash: b21abe376dc9b9ca0e8bcf26c5aec27723597706
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
int get_ENABLE(); 
int set_ENABLE(int); 
float get_Tension(); 


#endif // inodriver_user_h