//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\medir_y_enviar.py
///  Source class: Aparato
///  Generation timestamp: 2019-06-05T07:47:06.526517
///  Class code hash: b21abe376dc9b9ca0e8bcf26c5aec27723597706
///
/////////////////////////////////////////////////////////////



#include "inodriver_user.h"

int enabled;

void user_setup() {
  enabled = 0;
}

void user_loop() {
}
// COMMAND: ENABLE, FEAT: enable
int get_ENABLE() {
  return 0;
};

int set_ENABLE(int value) {
  return 0;
};


// COMMAND: Tension, FEAT: tension
float get_Tension() {
  return 0.0;
};


