//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\tpfinal\tpfinal_bn.py
///  Source class: Servo
///  Generation timestamp: 2019-06-19T03:38:37.831490
///  Class code hash: 17ef8b58725c6115f9b70a0e999c5d929b252103
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
int get_ENABLE(); 
int set_ENABLE(int); 
float get_Angulo(); 
int set_Angulo(float); 


#endif // inodriver_user_h