//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\lantz_servo.py
///  Source class: Servo
///  Generation timestamp: 2019-06-12T05:17:56.352396
///  Class code hash: ffca21f7b3cfb288e87f2bb172d571306d3676f6
///
/////////////////////////////////////////////////////////////


#include <Arduino.h>
#include "inodriver_user.h"

#include <Servo.h>

Servo myservo;  // create servo object to control a servo
// twelve servo objects can be created on most boards

float current = 0.0;    // variable to store the servo position

void user_setup() {
  myservo.attach(11);  // attaches the servo on pin 9 to the servo object
}

void user_loop() {
  
}

// COMMAND: Angulo, FEAT: angulo
float get_Angulo() {
  return current;
}

int set_Angulo(float value) {
  myservo.write((int)value);
  delay(5);
  current = value;
  return 0;
}


// COMMAND: ENABLE, FEAT: enable
int get_ENABLE() {
  return 0;
};

int set_ENABLE(int value) {
  return 0;
};


