//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\lantz_servo.py
///  Source class: Servo
///  Generation timestamp: 2019-06-12T05:17:56.332396
///  Class code hash: ffca21f7b3cfb288e87f2bb172d571306d3676f6
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_bridge_h
#define inodriver_bridge_h

#include <Arduino.h>

#include "SerialCommand.h"

#include "inodriver_user.h"

const char COMPILE_DATE_TIME[] = __DATE__ " " __TIME__;

void ok();
void error(const char*);
void error_i(int);
void bridge_loop();
void bridge_setup();

void getInfo();
void unrecognized(const char *);
void wrapperGet_Angulo(); 
void wrapperSet_Angulo(); 
void wrapperGet_ENABLE(); 
void wrapperSet_ENABLE(); 


#endif // inodriver_bridge_h