//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\lantz_servo.py
///  Source class: Servo
///  Generation timestamp: 2019-06-12T05:17:56.352396
///  Class code hash: ffca21f7b3cfb288e87f2bb172d571306d3676f6
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
float get_Angulo(); 
int set_Angulo(float); 
int get_ENABLE(); 
int set_ENABLE(int); 


#endif // inodriver_user_h