//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\medir_y_enviar.py
///  Source class: medir_y_enviar
///  Generation timestamp: 2019-06-05T05:11:06.780999
///  Class code hash: d2af6ce7368bde9eaff4946731656b9ed8606706
///
/////////////////////////////////////////////////////////////

#include "arduino.h"

#include "inodriver_user.h"

int analogPin = A0;
int valor = 0;
//int tensiones[100];
float tension=0;
int enviar=127;


void user_setup() {

}

void user_loop() {
   // put your main code here, to run repeatedly: 
  //float valor=tensiones[i];
  tension = analogRead(analogPin)* (255.0/ 1023.0);
  if (enviar<=tension) {
    enviar=enviar+1;
    analogWrite(9,enviar);
    }
  else {
    enviar=enviar-1;
    analogWrite(9,enviar);
  }   
  delay(1); 
// COMMAND: Tension, FEAT: tension
}

float get_Tension(void){
  tension = analogRead(analogPin)* (5.0/ 1023.0);  // read the input pin
  return tension;
}





