//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Publico.LABORATORIOS\Desktop\instrumentacion y control\arduino lantz\medir_y_enviar.py
///  Source class: medir_y_enviar
///  Generation timestamp: 2019-06-05T05:11:06.780999
///  Class code hash: d2af6ce7368bde9eaff4946731656b9ed8606706
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
float get_Tension(); 

#endif // inodriver_user_h
